/* This file is auto-generated by SST. Do not edit. */
// eslint-disable-next-line @typescript-eslint/ban-tslint-comment
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
